# Generated by Django 5.1.3 on 2025-01-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videodetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channelname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('like', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('video', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('channelphoto', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
